# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tkinder/probable-range',
                'doc_host': 'https://tkinder.github.io',
                'git_url': 'https://github.com/tkinder/tkinder/probable-range',
                'lib_path': 'tkinder/probable_range'},
  'syms': { 'probable_range.DJIA-probable-price-post-to-blogger': {},
            'probable_range.core': {'probable_range.core.foo': ('core.html#foo', 'probable_range/core.py')},
            'probable_range.djia-probable-price-pine-chart': {},
            'probable_range.generate_requirements': {}}}
